default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL").gsub("postgres","postgis")%>

development:
  <<: *default
  database: bionexo_development
test:
  <<: *default
  database: bionexo_test
production:
  <<: *default
  database: bionexo_production
