default: &default
  adapter: postgis
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  schema_search_path: public

development:
  <<: *default
  database: bionexo_development

test:
  <<: *default
  database: bionexo_test

production:
  <<: *default
  database: bionexo_production
  url: <%= ENV['DATABASE_URL'].sub(/^postgres/, "postgis") %>
